# Use same lts version as stack.yaml
FROM fpco/stack-build:lts-9.21

RUN mkdir -p /opt/build

WORKDIR /opt/build

COPY . .

# Install and build
RUN stack setup && \
    stack build && \
    stack build test --no-run-tests && \
    stack install ghcid hlint

# Run repl as default command
CMD ["stack", "repl"]
